spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/currency_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.sql

logging:
  level:
    root: INFO
    ru.Grom: DEBUG